### ISSUE TITLE
nnvg could not compiler tag v1.0.0rc4

### ISSUE THREAD

**Issue by Cherish-forever** [UAVCAN/public_regulated_data_types#106]
pydsdl._dsdl_definition.FileNameFormatError: /home/weig/temp/backup_code/public_regulated_data_types/uavcan/CoarseOrientation.uavcan: Invalid file name

master branch is ok, please check, or make a latest release tag.

**Comment by pavel-kirienko** [comment]
Nunavut cannot be used with v0. All new projects utilizing UAVCAN should adopt v1.

**Comment by Cherish-forever** [comment]
@pavel-kirienko  Thank you very much. will v1 protocol release coming soon?

**Comment by pavel-kirienko** [comment]
It is already released. Technically it is still beta but it is stable enough to build upon without risking breakage.

https://forum.uavcan.org/t/2020-recap-and-roadmap/1051
