### ISSUE TITLE
Suggestions and questions

### ISSUE THREAD

**Issue by ZLL6** [UAVCAN/public_regulated_data_types#119]
Question 1: In the file 1092.BatteryInfo.uavcan
I found that float16 remaining_capacity_wh # [Watt hours] Will be increasing during charging
float16 full_charge_capacity_wh # [Watt hours] Predicted battery capacity when it is fully charged. Falls with aging
The units of remaining_capacity_wh and full_charge_capacity_wh are Wh. Wh will produce a larger error. My suggestion here is to use Ah.
Question 2: In the 1091.CircuitStatus.uavcan file
In line 13 uint8 ERROR_FLAG_UNDERCURRENT = 8; What is the concept of undercurrent? The battery industry does not have this concept. I don’t know if I can explain what it means.

**Comment by pavel-kirienko** [comment]
Energy and electric charge represent completely different physical states and are not easily interchangeable. The higher-level system that consumes the data published by the smart battery is primarily interested in the energy estimates, not charge.

"Undercurrent" simply means that the current is lower than expected.

**Comment by ZLL6** [comment]
> Energy and electric charge represent completely different physical states and are not easily interchangeable. The higher-level system that consumes the data published by the smart battery is primarily interested in the energy estimates, not charge.
> 
> "Undercurrent" simply means that the current is lower than expected.

 "Undercurrent" simply means that the current is lower than expected. What does the expected. here mean？

**Comment by ZLL6** [comment]
> Energy and electric charge represent completely different physical states and are not easily interchangeable. The higher-level system that consumes the data published by the smart battery is primarily interested in the energy estimates, not charge.
> 
> "Undercurrent" simply means that the current is lower than expected.

 "Undercurrent" simply means that the current is lower than expected. What does the expected. here mean？

**Comment by pavel-kirienko** [comment]
>What does the expected. here mean？

The expected range is defined by the application.
